#######https://blog.frankel.ch/dockerfile-maven-based-github-projects/######
FROM alpine/git as clone
WORKDIR /app
RUN git clone https://github.com/spring-projects/spring-petclinic.git

FROM maven:3.5-jdk-8-alpine as build 
WORKDIR /app
COPY --from=clone /app/spring-petclinic /app
RUN mvn install

FROM jfrogqa/busybox as publish
WORKDIR /app
COPY --from=build /app/target/spring-petclinic-2.5.0-SNAPSHOT.jar /app
RUN curl -X PUT -u admin:Ram@R1537 -T spring-petclinic-2.5.0-SNAPSHOT.jar "http://3.15.40.197:8082/ui/admin/repositories/local/maven-demo-local/spring-petclinic-2.5.0-SNAPSHOT.jar"

FROM openjdk:8-jre-alpine as deploy
WORKDIR /app
EXPOSE 8080
ADD http://3.15.40.197:8082/ui/admin/repositories/local/maven-demo-local/spring-petclinic-2.5.0-SNAPSHOT.jar ./
ENTRYPOINT ["sh", "-c"]
CMD ["java -jar spring-petclinic-2.5.0-SNAPSHOT.jar"]


